name: Java CI with Maven - Test and package
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
on: [pull_request] # Ce workflow se déclenche sur un pull request dans le dépôt

jobs:
  TestAndPackage: # Nom du job : Test and package
    name: Test and package
    runs-on: ubuntu-latest # OS où s'exécute le job
    steps:
      - name: checkout@v4 #une tâche pour faire un checkout
        uses: actions/checkout@v4
      - name: setup-java@v4 #une tâche pour faire un setup
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: cache@v4Maven #une tâche pour faire un cache pour maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache SonarQube packages  #une tâche pour faire un cache pour sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: envoie_des_taches
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')